name: moj_pierszy_projekt
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.5
  permission_handler: ^11.0.0
  reorderables: ^0.6.0
  reorderable_grid_view: ^2.2.4
  



  # Inne
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  http: ^1.3.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo_foreground.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_foreground.png"
  adaptive_icon_background: "#66BB6A"
  adaptive_icon_foreground: "assets/logo_foreground.png"
