# Podfile
platform :ios, '13.0'

# CocoaPods analytics disables
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require_relative '../flutter_tools/bin/podhelper.rb'

target 'Runner' do
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
